
LOGIN_CODE = {
    LOGIN_OK = 1,
    LOGIN_WRONG_PWD = 2,
    LOGIN_ACCOUNT_UNEXIST = 3,
    LOGIN_SERVER_UNOPEN = 4,
    LOGIN_NAME_DUPLICATE = 5,
    LOGIN_PID_UNEXIST = 6,
    LOGIN_UNLOAD_ROLE = 7,
    LOGIN_ROLE_LIMIT = 8,
}

STATUS_LOGIN = {
    STATUS_INIT = 0,
    STATUS_ROLE = 1,
}

MAX_ROLE_LIMIT = 3
